### ISSUE TITLE
Version 0.3.1 release

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#382]
- [x] Glutin Mojave bug fix (#381): There's a showstopping bug that the PR fixes, which should get pushed out to crates.io sooner rather than later
- [x] impl Drawable Example (#379): This bit of documentation would be valuable to end users
- [x] Closing the application manually (#332): A small non-breaking API change
- [x] Remove std::env::home_dir (#384): The function is deprecated, and a third-party crate is the new standard
- [x] create-release on macOS (#388): This is a bit of inside-baseball, as only one person (me) needs to make releases, but it's good practice to have shell scripts work on any POSIX system
- [x] Example descriptions are not included on the website (#387): This means that things like the Camera example that require a bit of prompting are very opaque to the user
