### ISSUE TITLE
Version 0.3.3 Release

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#403]
- [x] Resize strategy parameter to preserve integer sizing (#317): This would allow applications to scale with pixel perfection
- [ ] Dynamic full-page sizing on web (#357): If an application is fullscreen, it would make sense if it took up the entire content area in the browser
- [ ] Support canvas touch events (#366): This would be a nice quality-of-life feature
- [x] Asset failing to load json files (#404): A fairly high-priority bug fix
- [ ] Rendering artifacts when rendering a font countdown (#405): Another high-priority bug
- [x] Line transforms are applied incorrectly (#406): A big with the transform order applied to lines

**Comment by ryanisaacg** [comment]
For now, at least, I've moved tracking issues to [projects](https://github.com/ryanisaacg/quicksilver/projects/4)
